using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Dotabuff_Parser
{
    public class Characters
    {
        public static List<string> characters = new List<string>
        {
            "abaddon",
            "alchemist",
            "ancient apparition",
            "anti-mage",
            "arc warden",
            "axe",
            "bane",
            "batrider",
            "beastmaster",
            "bloodseeker",
            "bounty hunter",
            "brewmaster",
            "bristleback",
            "broodmother",
            "centaur warrunner",
            "chaos knight",
            "chen",
            "clinkz",
            "clockwerk",
            "crystal maiden",
            "dark seer",
            "dark willow",
            "dawnbreaker",
            "dazzle",
            "death prophet",
            "disruptor",
            "doom",
            "dragon knight",
            "drow ranger",
            "earth spirit",
            "earthshaker",
            "elder titan",
            "ember spirit",
            "enchantress",
            "enigma",
            "faceless void",
            "grimstroke",
            "gyrocopter",
            "hoodwink",
            "huskar",
            "io",
            "invoker",
            "jakiro",
            "juggernaut",
            "keeper of the light",
            "kunkka",
            "leshrac",
            "lich",
            "lifestealer",
            "lina",
            "lion",
            "lone druid",
            "luna",
            "lycan",
            "magnus",
            "marci",
            "mars",
            "medusa",
            "meepo",
            "mirana",
            "monkey king",
            "muerta",
            "naga siren",
            "natures prophet",
            "necrophos",
            "night stalker",
            "nyx assassin",
            "ogre magi",
            "oracle",
            "outworld destroyer",
            "pangolier",
            "phantom assassin",
            "phantom lancer",
            "phoenix",
            "puck",
            "pudge",
            "pugna",
            "queen of pain",
            "razor",
            "riki",
            "rubick",
            "sand king",
            "shadow demon",
            "shadow fiend",
            "shadow shaman",
            "silencer",
            "skywrath mage",
            "slardar",
            "slark",
            "snapfire",
            "spectre",
            "spirit breaker",
            "storm spirit",
            "sven",
            "techies",
            "templar assassin",
            "terrorblade",
            "tidehunter",
            "timbersaw",
            "tinker",
            "tiny",
            "treant protector",
            "troll warlord",
            "tusk",
            "underlord",
            "undying",
            "ursa",
            "vengeful spirit",
            "venomancer",
            "viper",
            "visage",
            "void spirit",
            "warlock",
            "weaver",
            "windranger",
            "winter wyvern",
            "witch doctor",
            "wraith king",
            "zeus"
        };
    }
}
